### ISSUE TITLE
It doesnt seem to works on my fire fox

### ISSUE THREAD

**Issue by vannessqn** [cia-ulaval/MangaAutoTranslator#18]
newest firefox with Violentmonkey instead of Tamper, I download the script and installed it in violentmonkey (if its didnt work on this please consider support it man, Tamper is bloat Violent is better I think)
Then I used the Search by image -> search with google lens is this suppose to how you use it right? but yeah you said in the thread its act like original, the text doesnt rotated and its not zoom in

**Comment by PladsElsker** [comment]
The pipeline is still a WIP:
https://github.com/cia-ulaval/MangaAutoTranslator/blob/bc1753134cb92116f71503547554601492193639/manga_auto_translator/pipeline.py#L37

It's not fully functional for now. 
Also, this project is meant to be a CLI tool. 
You can follow the README.md instructions if you want to run it (let me know if I'm missing your point, I am genuenly confused when you say that you tried to use it in firefox).

**Comment by vannessqn** [comment]
Oh shit I think I posted on the wrong github page because I opened mutiple manga translator github programs at once, sorry man!
